version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_INTERNAL://kafka1:29092,PLAINTEXT_EXTERNAL://10.56.66.52:9092'
      KAFKA_LISTENERS: 'PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka2:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_INTERNAL://kafka2:29093,PLAINTEXT_EXTERNAL://10.56.66.52:9093'
      KAFKA_LISTENERS: 'PLAINTEXT_INTERNAL://0.0.0.0:29093,PLAINTEXT_EXTERNAL://0.0.0.0:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      # Expose the Kafka UI on port 9080 of the host machine
      - "9080:8080"
    depends_on:
      # Ensures Kafka UI starts only after the Kafka broker is running
      - kafka1
      - kafka2
    environment:
      # --- Kafka Cluster Configuration ---
      # Defines the connection to our Kafka cluster.
      # KAFKA_CLUSTERS_0_NAME: A display name for the cluster in the UI.
      KAFKA_CLUSTERS_0_NAME: 'local-kafka-cluster'
      # KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: The address of the Kafka broker.
      # 'kafka:9092' refers to the 'kafka' service defined above, on its internal Docker network port.
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka1:29092,kafka2:29093'
      # KAFKA_CLUSTERS_0_ZOOKEEPER: The address of the Zookeeper instance.
      # This is optional but helpful for some features.
      KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'